<a href="https://colab.research.google.com/github/dyou-wbg/meta_processing/blob/main/Character_based_clustering_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
# as of today
import datetime as dt
dt.date.today()
import os
import pandas as pd
from google.colab import drive
import csv
import os
directory = '/content/drive/MyDrive'
df_base = pd.read_csv(os.path.join(directory, 'All_titles.csv'))
df_base.rename(columns={'0': 'title'}, inplace=True)
df_base.drop(columns=['Unnamed: 0'], inplace=True)
df = df_base.sample(n=10000).dropna()
df.columns

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Index(['title'], dtype='object')

In [16]:
from string import printable
from collections import Counter
import numpy as np

printable_dict = {c:i for i,c in enumerate(printable)}

def vectorize(title):
    """ Returns a vector with counts for each printable character found in a title """
    cnt = Counter(title)
    array = [0 for _ in printable]+[0] # Last position is for nonprintable characters
    for c,n in cnt.items():
        if c in printable_dict:
            array[printable_dict[c]]=n
        else:
            array[-1]+=n # Update last position if it's not printable
    return np.array(array)

In [17]:
vects = []
for title in df.title:
    vects.append(vectorize(title))

In [18]:
%%time
threshold = 10
min_length = 20
# Iterate over title pairs
for i, v1 in enumerate(vects):
    if sum(v1[:-1]) > min_length: # Only above a minimum number of printable characters
        for j, v2 in enumerate(vects):
            if sum(v2[:-1]) > min_length:
                if i!=j:
                    l1 = np.linalg.norm((v1[:-1] - v2[:-1]), ord=1)
                    if l1 < threshold:
                        t1 = df.iloc[i].title
                        t2 = df.iloc[j].title
                        print(t1)
                        print(t2)
                        print('_'*100)

Cartels via the modiclus
Behavior and its causes
____________________________________________________________________________________________________
Funding the infrastructure
Discounting the Future
____________________________________________________________________________________________________
Σύγχρονες αντιλήψεις για την εξέλιξη των μέσων πληρωμής. Η κατάργηση των μετρητών και οι συνέπειές της. Θλιμμένα τα μάτια της Ευρώπης.
مبنای تئوریک دولت رفاه از دیدگاه پوپر (بررسی بنیان های فلسفی و نحوه شکل گیری وعملکرد دولت رفاه از دیدگاه کارل پوپر)
____________________________________________________________________________________________________
Σύγχρονες αντιλήψεις για την εξέλιξη των μέσων πληρωμής. Η κατάργηση των μετρητών και οι συνέπειές της. Θλιμμένα τα μάτια της Ευρώπης.
Описание несоответствия состояний информированных элементов среды деятельности для задач оценки безопасности и взаимодействия с позиции теорий нечетких множеств и не силовых взаимодействий
_______________________

In [8]:
# when sample = 2k
#%%time
#from sklearn.neighbors import KDTree
#tree = KDTree(np.array(vects), leaf_size=10, metric='cityblock')

CPU times: user 551 ms, sys: 136 ms, total: 687 ms
Wall time: 1.29 s


In [19]:
%%time
from sklearn.neighbors import KDTree
tree = KDTree(np.array(vects), leaf_size=10, metric='cityblock')

CPU times: user 116 ms, sys: 922 µs, total: 117 ms
Wall time: 117 ms


In [20]:
for i in range(len(vects)):
    dist, ind = tree.query(vects[i:i+1], k=3)
    print(dist)

Streaming output truncated to the last 5000 lines.
[[ 0. 28. 33.]]
[[ 0. 30. 31.]]
[[ 0. 14. 19.]]
[[ 0. 43. 44.]]
[[ 0. 19. 21.]]
[[ 0. 18. 18.]]
[[ 0. 43. 45.]]
[[ 0. 34. 35.]]
[[ 0. 19. 21.]]
[[ 0. 34. 34.]]
[[ 0. 27. 27.]]
[[ 0. 27. 28.]]
[[ 0. 32. 33.]]
[[ 0. 24. 27.]]
[[ 0. 23. 24.]]
[[ 0. 15. 17.]]
[[ 0. 23. 26.]]
[[ 0. 21. 22.]]
[[ 0. 22. 22.]]
[[ 0. 24. 27.]]
[[ 0. 23. 24.]]
[[ 0. 41. 41.]]
[[ 0. 26. 27.]]
[[ 0. 23. 23.]]
[[ 0. 22. 22.]]
[[ 0. 20. 26.]]
[[ 0. 21. 21.]]
[[ 0. 12. 12.]]
[[ 0. 26. 27.]]
[[ 0. 15. 24.]]
[[ 0. 27. 28.]]
[[ 0. 32. 34.]]
[[ 0. 14. 15.]]
[[ 0. 39. 40.]]
[[ 0. 23. 24.]]
[[ 0. 32. 34.]]
[[ 0. 15. 16.]]
[[ 0. 58. 64.]]
[[ 0. 27. 28.]]
[[ 0. 29. 30.]]
[[ 0. 26. 27.]]
[[ 0. 30. 31.]]
[[ 0. 14. 15.]]
[[ 0. 44. 47.]]
[[ 0. 18. 18.]]
[[ 0. 28. 28.]]
[[ 0. 14. 19.]]
[[ 0. 19. 22.]]
[[ 0. 18. 23.]]
[[ 0. 22. 23.]]
[[ 0. 33. 34.]]
[[ 0. 12. 12.]]
[[ 0. 19. 20.]]
[[ 0. 34. 34.]]
[[ 0. 21. 23.]]
[[ 0. 37. 38.]]
[[ 0. 15. 16.]]
[[ 0. 20. 21.]]
[[ 0. 31. 34.]]
[[ 0.

In [21]:

duplicate_rows = df[df.duplicated(subset='title')]
print(duplicate_rows)


                                                      title
1053159                                      At Close Range
471596                                            Editorial
10601686                                          Editorial
5834      Persuasive Advertising and Product Differentia...
8331533                                           Editorial
119442           [Notifiable Diseases and Mortality Tables]
10745515                   Uncertainty and Growth Disasters
2561043                                      Books Received
2028786   Price and quantity controls as facilitating de...
8122187                                        Book Reviews
811896                                       At Close Range


In [22]:
len(duplicate_rows)/len(df)

0.0011038635223281485